import React from 'react';
import Navbar from '../../components/Navbar';
import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <>
      <Navbar />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <div className="flex items-center justify-between mb-8 relative">
          <Link href="/en" className="flex items-center text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
            </svg>
            Back
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white absolute left-1/2 transform -translate-x-1/2">Privacy Policy</h1>
          <div className="w-20"></div> {/* This empty div helps balance the layout */}
        </div>
        
        <div className="space-y-6 text-gray-700 dark:text-gray-300">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Introduction</h2>
            <p className="mb-4">
            3ja.com (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, 
              and safeguard your information when you use our service.
            </p>
            <p>
              Please read this Privacy Policy carefully. By accessing or using our service, you acknowledge that you have read, understood, 
              and agree to be bound by all the terms outlined in this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Information We Collect</h2>
            <p className="mb-4">
              We collect the following types of information when you use our service:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Usage Data: Information about how you interact with our website, including pages visited, time spent, and actions taken.</li>
              <li>Device Information: Information about your device, including browser type, IP address, and operating system.</li>
              <li>Language Preferences: Your preferred language setting for viewing our website.</li>
            </ul>
            <p>
              Please note that our service does not require user accounts, so we do not collect personal account information such as names, email addresses, or passwords.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Cookies and Similar Technologies</h2>
            <p className="mb-4">
              We use cookies and similar technologies to enhance your experience on our platform. Cookies are small data files stored on your 
              device that help us improve our service and your experience, remember your preferences, and provide personalized content.
            </p>
            <p className="mb-4">
              We use the following types of cookies:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li><strong>Essential cookies:</strong> These cookies are necessary for the website to function properly and cannot be turned off in our systems.</li>
              <li><strong>Preference cookies:</strong> These cookies enable the website to remember your language preference (English or Traditional Chinese) and theme selection.</li>
              <li><strong>Analytical cookies:</strong> These cookies allow us to count visits and traffic sources through Google Analytics so we can measure and improve the performance of our site.</li>
              <li><strong>Advertising cookies:</strong> These cookies are used to show you relevant advertisements on our website and may be shared with advertising partners.</li>
            </ul>
            <p>
              You can control cookies through your browser settings. However, if you disable cookies, some features of our service may not function properly, such as your language preference settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Google Analytics</h2>
            <p className="mb-4">
              We use Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use our site. 
              The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers.
            </p>
            <p>
              Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity, and providing other 
              services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, 
              or where such third parties process the information on Google&apos;s behalf.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Advertising</h2>
            <p className="mb-4">
              Our website displays advertisements from third-party advertising networks. These advertisers may use cookies and similar technologies to collect 
              information about your browsing activities over time and across different websites. This information may be used to provide you with interest-based advertising.
            </p>
            <p>
              We do not control these third parties&apos; tracking technologies or how they may be used. If you have any questions about an advertisement, 
              you should contact the responsible advertiser directly.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">How We Use Your Information</h2>
            <p className="mb-4">
              We use the information we collect to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide, maintain, and improve our services</li>
              <li>Remember your language preferences (English or Traditional Chinese)</li>
              <li>Analyze website traffic and usage patterns</li>
              <li>Display relevant advertisements</li>
              <li>Personalize your experience on our platform</li>
              <li>Monitor and analyze trends, usage, and activities in connection with our services</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Data Security</h2>
            <p>
              We implement appropriate technical and organizational measures to protect the security of your personal information. 
              However, please be aware that no method of transmission over the Internet or method of electronic storage is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy 
              on this page and updating the &quot;Last Updated&quot; date. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-100">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at privacy@3ja.com.
            </p>
          </section>

          <div className="text-sm text-gray-500 dark:text-gray-400 pt-6 border-t border-gray-200 dark:border-gray-700">
            Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </div>
        </div>
      </div>
    </>
  );
} 